### ISSUE TITLE
Docker - check your Plex settings and try again

### ISSUE THREAD

**Issue by televisi** [se1exin/Cleanarr#100]
Hi,
I setup cleanarr from docker compose (as defined on the instruction page) on QNAP container station:
```
version: '3'

services:

  cleanarr:
    image: selexin/cleanarr:latest
    container_name: cleanarr
    hostname: cleanarr
    ports:
      - "5000:80"
    environment:
      - BYPASS_SSL_VERIFY=1
      - PLEX_TOKEN=somerandomstring
      - PLEX_BASE_URL=https://192.168.1.26:32400
      - LIBRARY_NAMES=Movies;TV
    volumes:
      - /share/Container-Data/cleanarr-new:/config
    restart: unless-stopped
```

Upon first run, this error is presented, what could gone wrong with this?
```
Failed to load content!
Please check your Plex settings and try again.
```
Thanks
