### ISSUE TITLE
I'm an idiot and need instruction please

### ISSUE THREAD

**Issue by darklogiccc** [se1exin/Cleanarr#128]
Hi, I pulled cleanarr into docker hub. I'm looking to find out what file is the config file that i would enter my data into. (ip, token and library names)
Thank you in advance!

**Comment by Simonk007** [comment]
use the docker compose
```
version: '3'

services:

  cleanarr:
    image: selexin/cleanarr:latest
    container_name: cleanarr
    hostname: cleanarr
    ports:
      - "5000:80"
    environment:
      - BYPASS_SSL_VERIFY=1
      - PLEX_TOKEN=somerandomstring
      - PLEX_BASE_URL=http://192.169.1.100:32400
      - LIBRARY_NAMES=Adult Movies;Kid Videos
    volumes:
      - /some/path/on/your/computer:/config
    restart: unless-stopped
```
