### ISSUE TITLE
Unable to start "Failed to load content!"

### ISSUE THREAD

**Issue by austempest** [se1exin/Cleanarr#55]
I've just set this up for the first time and cannot get it to work for me. Also can't find a discord to ask for support.

- i've confirmed 'allow media deletion' is enabled
- found plex token
- started via docker-compose
````
version: '3'

services:

  cleanarr:
    image: selexin/cleanarr:latest
    container_name: cleanarr
    hostname: cleanarr
    ports:
      - 8885:80
    environment:
      - BYPASS_SSL_VERIFY=1
      - PLEX_TOKEN=myplextoken
      - PLEX_BASE_URL=http://192.169.1.93:32400
      - LIBRARY_NAMES=Movies;Movies Kids;TV Shows;TV Shows Kids; TV Shows Older Kids;TV Shows Solo
    volumes:
      - /home/cleanarr:/config
    restart: unless-stopped
````

The container is within an LXC (ubuntu) on a proxmox node on IP 192.168.1.92

log files [https://pastebin.com/2HLQZ9g9](url)

**Comment by se1exin** [comment]
@austempest thanks for reporting, and for the log files!

Looks like the backend is timing out, which might be related to having many library names configured (I've only tested with 2 libraries - not as many as 6 sorry). Can you please try adding the following environment variable to your docker-compose?

```
PAGE_SIZE=20
```

As of a few days ago, Cleanarr queries Plex in pages/chunks - `PAGE_SIZE` determines how many media items to load per chunk. The default is 50 - so 6 x 50 = 300, which might be causing the backend process to run out of memory.

Let me know if lowering it to `20` helps at all (or even try as low as `10`, `5`, or `1`.

**Comment by austempest** [comment]
Thanks for the quick reply @se1exin.

Added the variable to docker compose, no change (I added PAGE_SIZE=10), log [here](https://pastebin.com/Vusr8dYE)

Changed the env to [PAGE_SIZE=1] log [here](https://pastebin.com/1yz2wAcU)

Changed to one library [LIBRARY_NAMES=Movies]; [PAGE_SIZE=10] log [here](https://pastebin.com/UXYzhzsq)

Other pieces of info
- [This is the error i get in the GUI  ](https://postimg.cc/pmpVJjLx)
-- could it be a plex token error?
--- i triple checked the plex token and it always comes out the same, tired the standard method you linked to via the plex website (view info, view xml, right of the address bar). Is there another way to get the plex token, or a way to check the one i'm using is correct?
- i saw '192.168.1.246' in the logs, it was the PC i was using. Not sure why it's being used if cleanarr is on *.1.92 and plex is on *.1.93

**Comment by se1exin** [comment]
@austempest Thanks for trying the `PAGE_SIZE` changes out - looks like it's not related to that.

It _could_ be a plex token issue, but it sounds like you are generating it correctly. Are you wrapping the token string in quotes in your docker-compose file? If it contains non-alphanumeric characters there may be some unintentional escaping or similar happening. E.g:

```
(BAD)
environment:
      - PLEX_TOKEN=myplextoken

(GOOD)
environment:
      - PLEX_TOKEN="myplextoken"
```

Also, seeing your computer's IP in webserver logs is very normal, it's logging the IP address of the computer that made the network request to the server.

**Comment by austempest** [comment]
@se1exin ... nope :(  it's going to be something really silly

my plex token had a couple of underscores and ended in one, so i wrapped it in inverted commas, [still no dice](https://pastebin.com/4TTR9WZm)

```
version: '3'
services:
  cleanarr:
    image: selexin/cleanarr:latest
    container_name: cleanarr
    hostname: cleanarr
    ports:
      - 8885:80
    environment:
      - BYPASS_SSL_VERIFY=1
      - PLEX_TOKEN="h_svthemiddlepartofmytokenkrU_"
      - PLEX_BASE_URL=http://192.169.1.93:32400
      - PAGE_SIZE=10
#      - LIBRARY_NAMES=Movies;Movies Kids;TV Shows;TV Shows Kids; TV Shows Older Kids;TV Shows Solo
      - LIBRARY_NAMES=Movies
    volumes:
      - /home/cleanarr:/config
    restart: unless-stopped
```
